FROM python:3.10.13-bookworm

WORKDIR /root/code

# Install dependencies

RUN pip3 install --upgrade pip
RUN pip3 install ipykernel
RUN pip3 install scikit-learn
RUN pip3 install numpy
RUN pip3 install pandas
RUN pip3 install seaborn
RUN pip3 install torch
RUN pip3 install matplotlib

# Copy the entire project to the working directory
COPY ./code /root/code  

# Start the Vite development server
CMD tail -f /dev/null



